Lang = {
    en = {
        already_masked = "You already have a mask on!",
        mask_on_default = "Default mask put on",
        mask_restored = "Mask put back on",
        no_mask = "You don't have a mask on!",
        mask_off_saved = "Mask taken off (saved)",
        invalid_command = "Invalid command. Use: /tmask on or /tmask off",
        enter_zone = "Mask removed in",
        exit_zone = "Mask restored",
    },
    ar = {
        already_masked = "أنت ترتدي قناعًا بالفعل!",
        mask_on_default = "تم ارتداء القناع الافتراضي",
        mask_restored = "تم ارتداء القناع المحفوظ",
        no_mask = "أنت لا ترتدي قناعًا!",
        mask_off_saved = "تم خلع القناع (محفوظ)",
        invalid_command = "أمر غير صالح. استخدم: /tmask on أو /tmask off",
        enter_zone = "تم خلع القناع في",
        exit_zone = "تم ارتداء القناع مرة أخرى",
    },
    es = {
        already_masked = "¡Ya llevas una máscara puesta!",
        mask_on_default = "Máscara predeterminada puesta",
        mask_restored = "Máscara guardada puesta",
        no_mask = "¡No llevas máscara!",
        mask_off_saved = "Máscara quitada (guardada)",
        invalid_command = "Comando inválido. Usa: /tmask on o /tmask off",
        enter_zone = "Máscara removida en",
        exit_zone = "Máscara restaurada",
    },
    fr = {
        already_masked = "Vous avez déjà un masque!",
        mask_on_default = "Masque par défaut mis",
        mask_restored = "Masque sauvegardé remis",
        no_mask = "Vous ne portez pas de masque!",
        mask_off_saved = "Masque enlevé (sauvegardé)",
        invalid_command = "Commande invalide. Utilisez: /tmask on ou /tmask off",
        enter_zone = "Masque retiré dans",
        exit_zone = "Masque restauré",
    },
    de = {
        already_masked = "Du trägst bereits eine Maske!",
        mask_on_default = "Standardmaske aufgesetzt",
        mask_restored = "Gespeicherte Maske aufgesetzt",
        no_mask = "Du trägst keine Maske!",
        mask_off_saved = "Maske abgenommen (gespeichert)",
        invalid_command = "Ungültiger Befehl. Verwende: /tmask on oder /tmask off",
        enter_zone = "Maske entfernt in",
        exit_zone = "Maske wiederhergestellt",
    },
    ru = {
        already_masked = "У вас уже есть маска!",
        mask_on_default = "Маска по умолчанию надета",
        mask_restored = "Сохранённая маска надета",
        no_mask = "На вас нет маски!",
        mask_off_saved = "Маска снята (сохранена)",
        invalid_command = "Неверная команда. Используйте: /tmask on или /tmask off",
        enter_zone = "Маска снята в",
        exit_zone = "Маска восстановлена",
    },
    pt = {
        already_masked = "Você já está usando uma máscara!",
        mask_on_default = "Máscara padrão colocada",
        mask_restored = "Máscara salva colocada",
        no_mask = "Você não está usando máscara!",
        mask_off_saved = "Máscara removida (salva)",
        invalid_command = "Comando inválido. Use: /tmask on ou /tmask off",
        enter_zone = "Máscara removida em",
        exit_zone = "Máscara restaurada",
    },
    zh = {
        already_masked = "你已经戴上面具了！",
        mask_on_default = "戴上了默认面具",
        mask_restored = "戴上了保存的面具",
        no_mask = "你没有戴面具！",
        mask_off_saved = "面具已取下（已保存）",
        invalid_command = "无效命令。使用：/tmask on 或 /tmask off",
        enter_zone = "面具已在以下区域移除",
        exit_zone = "面具已恢复",
    },
    ja = {
        already_masked = "あなたはすでにマスクを着用しています！",
        mask_on_default = "デフォルトのマスクを装着",
        mask_restored = "保存されたマスクを装着",
        no_mask = "マスクを着用していません！",
        mask_off_saved = "マスクを外しました（保存済み）",
        invalid_command = "無効なコマンド。使用法：/tmask on または /tmask off",
        enter_zone = "マスクを外した場所",
        exit_zone = "マスクを復元しました",
    },
    hi = {
        already_masked = "आप पहले से ही मास्क पहने हुए हैं!",
        mask_on_default = "डिफ़ॉल्ट मास्क पहना हुआ",
        mask_restored = "सहेजा गया मास्क पहना हुआ",
        no_mask = "आपने मास्क नहीं पहना है!",
        mask_off_saved = "मास्क उतारा गया (सहेजा गया)",
        invalid_command = "अमान्य आदेश। उपयोग करें: /tmask on या /tmask off",
        enter_zone = "मास्क हटाया गया",
        exit_zone = "मास्क बहाल किया गया",
    },
    tr = {
        already_masked = "Zaten bir maskeniz var!",
        mask_on_default = "Varsayılan maske takıldı",
        mask_restored = "Kayıtlı maske takıldı",
        no_mask = "Maskeniz yok!",
        mask_off_saved = "Maske çıkarıldı (kaydedildi)",
        invalid_command = "Geçersiz komut. Kullanım: /tmask on veya /tmask off",
        enter_zone = "Maskenin kaldırıldığı yer",
        exit_zone = "Maske geri yüklendi",
    },
    it = {
        already_masked = "Hai già una maschera!",
        mask_on_default = "Maschera predefinita indossata",
        mask_restored = "Maschera salvata indossata",
        no_mask = "Non stai indossando una maschera!",
        mask_off_saved = "Maschera rimossa (salvata)",
        invalid_command = "Comando non valido. Usa: /tmask on o /tmask off",
        enter_zone = "Maschera rimossa in",
        exit_zone = "Maschera ripristinata",
    }
}

CurrentLang = Lang["en"] -- ("es", "fr", etc.)